plugins {
    id 'com.android.application'
}

// 🎯 强制排除 Kotlin 依赖，防止 AAR 把 2MB 的 Kotlin 垃圾带进来
configurations.all {
    exclude group: 'org.jetbrains.kotlin'
    exclude group: 'org.jetbrains'
}

android {
    namespace 'com.batterywhitelist'
    compileSdk 37

    signingConfigs {
        release {
            storeFile file(System.getenv("KEYSTORE_PATH") ?: "release.jks")
            storePassword System.getenv("KEYSTORE_PASSWORD")
            keyAlias System.getenv("KEY_ALIAS")
            keyPassword System.getenv("KEY_PASSWORD")
                        
        }
        
        
        
        
    }

    defaultConfig {
        applicationId "com.batterywhitelist"
        minSdk 29
        targetSdk 37
        versionCode 18
        versionName "1.18"
    }

    buildTypes {
        release {
            minifyEnabled false       
            shrinkResources false      
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'),
                    'proguard-rules.pro'
            signingConfig signingConfigs.release
        }
    }

    // 🎯 新增：关闭 Release 包的 Lint 致命检查
    lint {
        checkReleaseBuilds false
        abortOnError false
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }

    packaging {
        resources {
            excludes += ['META-INF/MANIFEST.MF']
        }
    }
}

dependencies {
    compileOnly 'io.github.libxposed:api:102.0.0@aar'
}